version: '3'
services:
  fluig1:
    image: your-fluig-image
    ports:
      - "8080:8080"
  fluig2:
    image: your-fluig-image
    ports:
      - "8081:8081"
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/fluig.conf:/etc/nginx/conf.d/default.conf
